### ISSUE TITLE
delay的方案

### ISSUE THREAD

**Issue by painson** [yjfnypeu/EasyThread#1]
个人觉得通过在runnable的run方法sleep来达到delay的方案不是很好，会阻塞到其他线程的执行

**Comment by yjfnypeu** [comment]
嗯，经你这么提醒。这个的实现的确不太好，近期会抽空想想别的实现方案。

**Comment by yjfnypeu** [comment]
[0.6.0版本](https://github.com/yjfnypeu/EasyThread/releases/tag/0.6.0)已替换实现方案。解决了此问题。

**Comment by painson** [comment]
＼(＞０＜)／
